Allow subdirectories for add & delete granules
fmidev/geoserver-rest pull request #20
Opened 2023-10-03 06:28 UTC by ritvje

Add a config option that allows keeping the subpath given in arguments when adding granules. 

E.g. if config file has

```yaml
geoserver_target_dir: /smartmet/radar/geotiff/radar-optclass/
```
if the filepath for `add_granule.py` is given as `fivih_3067/20230926_1300_fivih_ppi-0.3_optclass.tif`, the filepath is interpreted as 

`/smartmet/radar/geotiff/radar-optclass/fivih_3067/20230926_1300_fivih_ppi-0.3_optclass.tif`

2023-10-03 07:57 UTC, pnuu requested changes
This seems to include also the changes in #19 . Please include only the changes of the new feature so that the changes still needed for #19 are not needed to be added also in this one.

2023-10-03 11:41 UTC, lahtinep reviewed
Just a couple of comments that would simplify the configs a bit for cases where sub directories don't need to be handled.

I'll also push some additional tests for `georest.utils.convert_file_path()` to this branch in a moment when I've finalized them.

2023-10-03 11:41 UTC, lahtinep commented on georest/__init__.py
> +    fname = utils.convert_file_path(config, fname_in, keep_subpath=config["keep_subpath"])
Could also be
```suggestion
    fname = utils.convert_file_path(config, fname_in, keep_subpath=config.get("keep_subpath", False))
```
so forgetting the extra option from the config doesn't cause a crash.

2023-10-03 11:41 UTC, lahtinep commented on georest/__init__.py
> +    fs_path = utils.convert_file_path(config, gs_location, inverse=True, keep_subpath=config["keep_subpath"])
```suggestion
    fs_path = utils.convert_file_path(config, gs_location, inverse=True, keep_subpath=config.get("keep_subpath", False))
```

2023-10-03 11:41 UTC, lahtinep commented on georest/utils.py
> +def convert_file_path(config, file_path, inverse=False, keep_subpath=False):
Apparently I haven't had a test case for this function, but we could add something now to `test_utils.py`. I'll write some and push them to this branch in a moment.

2023-10-03 12:07 UTC, lahtinep commented
@ritvje do you think the cases I added for `keep_subpath=True` tests for `georest.utils.convert_file_path()` make sense?

2023-10-03 12:56 UTC, ritvje commented
Looks good. Your version of the inverse option of `georest.utils.convert_file_path()` is much better, I was struggling a bit with that.

2023-10-04 06:07 UTC, lahtinep approved these changes
Looking good, merging.

2023-10-04 06:07 UTC, merged